platform :ios, '7.0'

pod 'AFNetworking', '~> 2.3.1'
pod 'ReactiveViewModel', '~> 0.2'
pod 'AFNetworking-RACExtensions', '~> 0.1.6'
pod 'CocoaLumberjack', '~> 2.0.0-beta'
pod 'CocoaAsyncSocket', '~> 7.3.5'
pod 'Reachability', '~> 3.1.1'
pod 'libextobjc', '~> 0.4'
pod 'NSObject-ObjectMap', '~> 2.3.1'

target :StudySwiftAPP, :exclusive => true  do  
pod 'MBProgressHUD', '~> 0.9'
pod 'MMDrawerController', '~> 0.5.7'
pod 'ActionSheetPicker', '~> 1.0.6'
pod 'KxMenu', '~> 1'
end

target :StudySwiftAPPTests, :exclusive => true  do  
pod 'OCMock', '~> 3.0.2'
end